spring:
  application:
    name: integration-test
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: none

eureka:
  client:
    register-with-eureka: false

product:
  userName: productUser
  password: productPassword
company:
  userName: companyUser
  password: companyPassword

feign.httpclient.enabled: true
