spring:
  application:
    name: integration-test
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: none

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://user:password@localhost:8761/eureka}
    healthcheck:
      enabled: false
  instance:
    secure-port-enabled: ${EUREKA_SECURE:false}
    non-secure-port-enabled: ${EUREKA_NOSECURE:true}

product:
  userName: user
  password: password
company:
  userName: user
  password: password

feign.httpclient.enabled: true
