services:

  product-postgresql:
    image: postgres:14.1
    environment:
      - POSTGRES_DB=db_product
      - POSTGRES_USER=product
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - "./postgresql:/docker-entrypoint-initdb.d"

  product-myadmin:
    image:  bitnami/phppgadmin-archived
    environment:
      - DATABASE_HOST=product-postgresql
    ports:
      - '8080:80'
      - '443:8443'

  product-eureka:
    image: francescofiora-product-eureka
    environment:
      - "EUREKA_SERVER=product-eureka"
    ports:
      - "8761:8761"

  product-gateway:
    image: francescofiora-product-gateway
    environment:
      - "EUREKA_URI=http://eurekaUser:eurekaPassword@product-eureka:8761/eureka"
    ports:
      - "3007:8080"
