server:
  port: 8761
  servlet:
    context-path: /

spring:
  security:
    user:
      name: ${EUREKA_USER:eurekaUser}
      password: ${EUREKA_PASSWORD:eurekaPassword}

management:
  endpoints:
    web:
     base-path: /actuator
     exposure:
       include: info,health,metrics,prometheus

eureka:
  instance:
    hostname: ${EUREKA_SERVER:localhost}
    metadata-map:
      metrics.path: /actuator/prometheus
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
